openapi: 3.0.0
info:
  title: "Dead Simple Search API"
  contact:
    email: giorgoskalmoukis@gmail.com
  version: 1.0.0
servers:
  - url: "http://127.0.0.1:8000/api"
    description: Local
paths:
  /listings:
    $ref: "./paths/listings/Listing.yaml"
  /listings/{id}:
    $ref: "./paths/listings/ListingId.yaml"
  /content/locations:
    $ref: "./paths/content/Location.yaml"
  /content/types:
    $ref: "./paths/content/Type.yaml"
  /content/availabilities:
    $ref: "./paths/content/Availability.yaml"